define(function(require, exports, module) {

  var Fixtures = {};
  
  Fixtures['w9zCNnEbfC'] = {
      "camera": {
          "height": "0",
          "initialX": "-15",
          "initialY": "-30",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "0.58",
          "timeOffset": "100",
          "translate": true,
          "translateX": "-90",
          "translateXSpeed": "5000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "xyRatio": "1"
      },
      "createdAt": "2014-12-24T15:29:15.795Z",
      "device": "1136x640",
      "hiddenOverflow": false,
      "objectId": "w9zCNnEbfC",
      "page": "ship",
      "popups": [{
          "height": "1",
          "initialX": "0",
          "initialY": "0",
          "name": "background",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": false,
          "translateX": "0",
          "translateXSpeed": "1000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/22and23/background.png",
          "xyRatio": "1"
      }, {
          "height": "2",
          "initialX": "-200",
          "initialY": "-200",
          "name": "wave1",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "1281",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": true,
          "translateX": 100,
          "translateXSpeed": 2000,
          "translateY": "30",
          "translateYSpeed": 1000,
          "url": "/content/images/pages/22and23/waves.png",
          "xyRatio": "1"
      }, {
          "height": "3",
          "initialX": "-200",
          "initialY": "-200",
          "name": "wave2",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": true,
          "translateX": 100,
          "translateXSpeed": 2000,
          "translateY": "30",
          "translateYSpeed": 1000,
          "url": "/content/images/pages/22and23/waves.png",
          "xyRatio": "1"
      }, {
          "height": "4",
          "initialX": "0",
          "initialY": "0",
          "name": "ship",
          "rotate": true,
          "rotateAngle": "60",
          "rotateSpeed": 2000,
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translateX": "0",
          "translateXSpeed": "1000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/22and23/ship.png",
          "xyRatio": "1"
      }, {
          "height": "5",
          "initialX": "0",
          "initialY": "0",
          "name": "main_pirate",
          "rotate": true,
          "rotateAngle": "80",
          "rotateSpeed": 2000,
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": false,
          "translateX": -20,
          "translateXSpeed": "2000",
          "translateY": 0,
          "translateYSpeed": 1000,
          "url": "/content/images/pages/22and23/main_pirate.png",
          "xyRatio": "1"
      }, {
          "height": "6",
          "initialX": "0",
          "initialY": "0",
          "name": "george",
          "rotate": true,
          "rotateAngle": "80",
          "rotateSpeed": 2000,
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "2000",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": false,
          "translateX": 20,
          "translateXSpeed": "2000",
          "translateY": 0,
          "translateYSpeed": 1000,
          "url": "/content/images/pages/22and23/george.png",
          "xyRatio": "1"
      }, {
          "height": "7",
          "initialX": "0",
          "initialY": "0",
          "name": "front_rope",
          "rotate": true,
          "rotateAngle": "60",
          "rotateSpeed": "2000",
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "2000",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": false,
          "translateX": "0",
          "translateXSpeed": "1000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/22and23/front_rope.png",
          "xyRatio": "1"
      }],
      "updatedAt": "2015-01-08T15:11:40.335Z"
  };

  Fixtures['GjENlwcbMb'] = {
      "camera": {
          "height": "0",
          "initialX": "-15",
          "initialY": "-30",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "0.58",
          "timeOffset": "100",
          "translate": true,
          "translateX": "-90",
          "translateXSpeed": "5000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "xyRatio": "1"
      },
      "createdAt": "2014-12-30T13:30:04.206Z",
      "device": "1136x640",
      "hiddenOverflow": false,
      "objectId": "GjENlwcbMb",
      "page": "street",
      "popups": [{
          "height": "1",
          "initialX": "0",
          "initialY": "0",
          "name": "background",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": false,
          "translateX": "0",
          "translateXSpeed": "1000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/16/background.png",
          "xyRatio": "1"
      }, {
          "height": "3",
          "initialX": "-200",
          "initialY": "-200",
          "name": "car",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "1281",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": true,
          "translateX": 100,
          "translateXSpeed": 2000,
          "translateY": "30",
          "translateYSpeed": 1000,
          "url": "/content/images/pages/16/car.png",
          "xyRatio": "1"
      }, {
          "height": "2",
          "initialX": "-200",
          "initialY": "-200",
          "name": "road",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": true,
          "translateX": 100,
          "translateXSpeed": 2000,
          "translateY": "30",
          "translateYSpeed": 1000,
          "url": "/content/images/pages/16/road.png",
          "xyRatio": "1"
      }],
      "updatedAt": "2014-12-30T13:37:24.294Z"
  };

  Fixtures['FnTu1Egg5v'] = {
      "camera": {
          "height": "0",
          "initialX": "-15",
          "initialY": "-30",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "0.58",
          "timeOffset": "100",
          "translate": true,
          "translateX": "-90",
          "translateXSpeed": "5000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "xyRatio": "1"
      },
      "createdAt": "2014-12-30T13:33:24.897Z",
      "device": "1136x640",
      "hiddenOverflow": false,
      "objectId": "FnTu1Egg5v",
      "page": "hands",
      "popups": [{
          "height": "1",
          "initialX": "0",
          "initialY": "0",
          "name": "background",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": false,
          "translateX": "0",
          "translateXSpeed": "1000",
          "translateY": "0",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/19/background.png",
          "xyRatio": "1"
      }, {
          "height": "2",
          "initialX": "-200",
          "initialY": "-200",
          "name": "hand1",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "1281",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": true,
          "translateX": 100,
          "translateXSpeed": 2000,
          "translateY": "30",
          "translateYSpeed": 1000,
          "url": "/content/images/pages/19/hand01.png",
          "xyRatio": "1"
      }, {
          "height": "3",
          "initialX": "-200",
          "initialY": "-200",
          "name": "hand2",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "scaleX": "1",
          "scaleY": "1",
          "timeOffset": "0",
          "timer": {
              "initialTime": 1419434956210
          },
          "translate": true,
          "translateX": 100,
          "translateXSpeed": 2000,
          "translateY": "30",
          "translateYSpeed": 1000,
          "url": "/content/images/pages/19/hand02.png",
          "xyRatio": "1"
      }, {
          "height": "4",
          "initialX": "200",
          "initialY": "200",
          "name": "hand3",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "timeOffset": "0",
          "translate": true,
          "translateX": "100",
          "translateXSpeed": "2000",
          "translateY": "30",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/19/hand03.png",
          "xyRatio": "1"
      }, {
          "height": "5",
          "initialX": "200",
          "initialY": "200",
          "name": "hand4",
          "rotateAngle": "100",
          "rotateSpeed": "2000",
          "scale": "1.5",
          "timeOffset": "0",
          "translate": true,
          "translateX": "100",
          "translateXSpeed": "2000",
          "translateY": "30",
          "translateYSpeed": "1000",
          "url": "/content/images/pages/19/hand04.png",
          "xyRatio": "1"
      }],
      "updatedAt": "2014-12-30T13:46:43.657Z"
  };

  module.exports = Fixtures;

});